export NCCL_DEBUG=INFO
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export TORCH_NCCL_BLOCKING_WAIT=1
export NCCL_IB_DISABLE=1
export NCCL_SOCKET_IFNAME=ens7

torchrun --standalone --nproc_per_node=8  train.py \
    --dataset=openwebtext \
    --data_dir=nanoGPT/data/openwebtext \
    --out_dir=out_ebt_openwebtext \
    --resume_latest=True \
    --max_steps=1000000 \
    --max_scheduling_steps=1000000 \
    --warm_up_steps=2000 \
    --eval_interval=5000 \
    --batch_size_per_device=1 \
    --accumulate_grad_batches=1 \
    --context_length=512 \
    --num_transformer_blocks=24 \
    --multiheaded_attention_heads=16 \
    --embedding_dim=1024 \
    --tokenizer=gpt2 \
    --gpus=8 \
    --distributed_strategy=ddp \
    --mcmc_num_steps=2 \
    --mcmc_replay_buffer_size=48 \
    --mcmc_step_size=60.0 \
    --normalize_initial_condition=True \
    --clamp_futures_grad=True 